/**
 * Dumps all DB-backed content tables into prisma/content-seed.sql so fresh
 * environments can be repopulated (after `prisma db push` + `db:seed`):
 *   psql "$DATABASE_URL" -f prisma/content-seed.sql
 *
 * Run: npx tsx scripts/dump-content.ts
 */
import { PrismaClient } from "@prisma/client";
import { CONTENT_REGISTRY } from "../lib/content-registry";
import { writeFileSync } from "fs";

const prisma = new PrismaClient();

function sql(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  return "'" + String(value).replace(/'/g, "''") + "'";
}

async function main() {
  const parts: string[] = [
    "-- NihoLearn content seed (generated by scripts/dump-content.ts)",
    "-- Applies after `npx prisma db push` + `npm run db:seed` (kana reference).",
    "",
  ];

  for (const [type, entry] of Object.entries(CONTENT_REGISTRY)) {
    const model = (prisma as any)[entry.model];
    const rows: Record<string, unknown>[] = await model.findMany();
    if (rows.length === 0) continue;

    const table = `"${entry.model.charAt(0).toUpperCase()}${entry.model.slice(1)}"`;
    parts.push(`-- ${type} (${rows.length} rows)`);

    for (const row of rows) {
      const cols = Object.keys(row).map((c) => `"${c === "pairType" ? "pairType" : c}"`).join(", ");
      const vals = Object.values(row).map(sql).join(", ");
      parts.push(`INSERT INTO ${table} (${cols}) VALUES (${vals}) ON CONFLICT DO NOTHING;`);
    }
    parts.push("");
  }

  writeFileSync("prisma/content-seed.sql", parts.join("\n"));
  console.log("Wrote prisma/content-seed.sql");
}

main()
  .catch((e) => { console.error(e); process.exitCode = 1; })
  .finally(() => prisma.$disconnect());
